title: PSP Homebrew Community Wiki
url: "https://psp-homebrew-community.github.io/wiki"
description: "A community-driven wiki and resource hub for everything related to PSP homebrew, modding, and development."
